name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Update Deployment Stage
        run: |
          if grep -q '"Development"' config.json; then
            sed -i 's/"Development"/"Testing"/g' config.json
          elif grep -q '"Testing"' config.json; then
            sed -i 's/"Testing"/"Production"/g' config.json
          else
            sed -i 's/"Production"/"Development"/g' config.json
          fi

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add config.json
          git commit -m "Updated deployment stage"
          git push
